services:
  - type: web
    name: document-to-summary-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn doc_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
